"""Unit tests for the pr_clean stripper (pr_clean/stripper.py).

Covers:

* :class:`~pr_clean.stripper.StripResult` dataclass properties.
* :func:`~pr_clean.stripper.strip_matches` convenience function.
* :func:`~pr_clean.stripper.strip_result` convenience function.
* :class:`~pr_clean.stripper.Stripper` for various block types.
* Blank-line collapsing and trailing-whitespace stripping.
* Overlapping span deduplication.
* Edge cases: empty text, no matches, matches-only text.
* Integration with the scanner fixture.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import List

import pytest

from pr_clean.scanner import ScanMatch, Scanner
from pr_clean.stripper import (
    Stripper,
    StripResult,
    _build_non_overlapping_spans,
    _collapse_excess_blank_lines,
    _expand_span_to_full_lines,
    strip_matches,
    strip_result,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "sample_pr_body.md"


@pytest.fixture()
def sample_text() -> str:
    return FIXTURE_PATH.read_text(encoding="utf-8")


@pytest.fixture()
def default_scanner() -> Scanner:
    return Scanner.from_defaults()


@pytest.fixture()
def copilot_block_text() -> str:
    return (
        "Intro line.\n"
        "START COPILOT CODING AGENT TIPS\n"
        "- Tip one\n"
        "- Tip two\n"
        "END COPILOT CODING AGENT TIPS\n"
        "Outro line.\n"
    )


@pytest.fixture()
def copilot_block_matches(copilot_block_text: str, default_scanner: Scanner) -> List[ScanMatch]:
    return default_scanner.scan(copilot_block_text)


# ---------------------------------------------------------------------------
# _collapse_excess_blank_lines helper
# ---------------------------------------------------------------------------


class TestCollapseExcessBlankLines:
    def test_three_blank_lines_collapsed_to_two(self) -> None:
        text = "a\n\n\n\nb"
        result = _collapse_excess_blank_lines(text)
        assert result == "a\n\nb"

    def test_two_blank_lines_preserved(self) -> None:
        text = "a\n\n\nb"
        result = _collapse_excess_blank_lines(text)
        assert result == "a\n\nb"

    def test_single_blank_line_preserved(self) -> None:
        text = "a\n\nb"
        result = _collapse_excess_blank_lines(text)
        assert result == "a\n\nb"

    def test_no_blank_lines_unchanged(self) -> None:
        text = "a\nb\nc"
        result = _collapse_excess_blank_lines(text)
        assert result == text

    def test_many_consecutive_blanks(self) -> None:
        text = "a" + "\n" * 10 + "b"
        result = _collapse_excess_blank_lines(text)
        assert "\n" * 3 not in result


# ---------------------------------------------------------------------------
# _expand_span_to_full_lines helper
# ---------------------------------------------------------------------------


class TestExpandSpanToFullLines:
    def test_single_line_match_expanded(self) -> None:
        text = "line one\nGENERATED BY COPILOT\nline three\n"
        # 'GENERATED BY COPILOT' starts at offset 9 (after 'line one\n')
        start = text.index("GENERATED")
        end = start + len("GENERATED BY COPILOT")
        exp_start, exp_end = _expand_span_to_full_lines(text, start, end, strip_full_block=True)
        # The expanded region should start at the beginning of the line.
        assert text[exp_start] == "G"  # first char of the matched line
        # Expanded end should consume the trailing newline.
        assert exp_end > end

    def test_no_expansion_when_strip_full_block_false(self) -> None:
        text = "line one\nGENERATED\nline three\n"
        start = text.index("GENERATED")
        end = start + len("GENERATED")
        exp_start, exp_end = _expand_span_to_full_lines(text, start, end, strip_full_block=False)
        assert exp_start == start
        assert exp_end == end

    def test_expansion_at_start_of_text(self) -> None:
        text = "MATCH\nmore text\n"
        start, end = 0, len("MATCH")
        exp_start, exp_end = _expand_span_to_full_lines(text, start, end, strip_full_block=True)
        assert exp_start == 0

    def test_expansion_at_end_of_text(self) -> None:
        text = "some text\nMATCH"
        start = text.index("MATCH")
        end = len(text)
        exp_start, exp_end = _expand_span_to_full_lines(text, start, end, strip_full_block=True)
        assert exp_end <= len(text) + 1  # May consume up to the end.


# ---------------------------------------------------------------------------
# _build_non_overlapping_spans helper
# ---------------------------------------------------------------------------


class TestBuildNonOverlappingSpans:
    def _make_match(self, start: int, end: int, name: str = "p") -> ScanMatch:
        """Build a minimal ScanMatch for span testing."""
        from pr_clean.patterns import get_pattern_by_name, Severity

        pattern = get_pattern_by_name("copilot_agent_tips_block")
        assert pattern is not None
        return ScanMatch(
            pattern_name=name,
            pattern=pattern,
            matched_text="x" * (end - start),
            line_start=1,
            line_end=1,
            char_start=start,
            char_end=end,
            severity=Severity.HIGH,
            confidence=0.9,
        )

    def test_non_overlapping_spans_preserved(self) -> None:
        matches = [
            self._make_match(0, 10, "a"),
            self._make_match(20, 30, "b"),
        ]
        spans = _build_non_overlapping_spans(matches)
        assert len(spans) == 2
        assert spans[0][0] == 0
        assert spans[1][0] == 20

    def test_overlapping_spans_merged(self) -> None:
        matches = [
            self._make_match(0, 15, "a"),
            self._make_match(10, 25, "b"),
        ]
        spans = _build_non_overlapping_spans(matches)
        assert len(spans) == 1
        assert spans[0][0] == 0
        assert spans[0][1] == 25

    def test_identical_spans_deduplicated(self) -> None:
        matches = [
            self._make_match(5, 15, "a"),
            self._make_match(5, 15, "b"),
        ]
        spans = _build_non_overlapping_spans(matches)
        assert len(spans) == 1

    def test_empty_matches_returns_empty(self) -> None:
        assert _build_non_overlapping_spans([]) == []

    def test_adjacent_spans_not_merged(self) -> None:
        matches = [
            self._make_match(0, 10, "a"),
            self._make_match(10, 20, "b"),
        ]
        spans = _build_non_overlapping_spans(matches)
        assert len(spans) == 2


# ---------------------------------------------------------------------------
# StripResult
# ---------------------------------------------------------------------------


class TestStripResult:
    def test_changed_true_when_text_differs(self) -> None:
        r = StripResult(
            original_text="original",
            clean_text="clean",
            removed_spans=[(0, 4, "p")],
        )
        assert r.changed is True

    def test_changed_false_when_text_identical(self) -> None:
        r = StripResult(
            original_text="same",
            clean_text="same",
            removed_spans=[],
        )
        assert r.changed is False

    def test_match_count(self) -> None:
        r = StripResult(
            original_text="x",
            clean_text="",
            removed_spans=[(0, 1, "p1"), (2, 3, "p2")],
        )
        assert r.match_count == 2

    def test_to_dict_keys(self) -> None:
        r = StripResult(original_text="a", clean_text="b", removed_spans=[])
        d = r.to_dict()
        assert set(d.keys()) == {"changed", "match_count", "removed_spans", "clean_text"}

    def test_to_dict_removed_spans_structure(self) -> None:
        r = StripResult(
            original_text="abcde",
            clean_text="",
            removed_spans=[(0, 5, "my_pattern")],
        )
        d = r.to_dict()
        assert len(d["removed_spans"]) == 1
        span = d["removed_spans"][0]
        assert span["char_start"] == 0
        assert span["char_end"] == 5
        assert span["pattern_name"] == "my_pattern"


# ---------------------------------------------------------------------------
# Stripper.strip — core behaviour
# ---------------------------------------------------------------------------


class TestStripperCoreStripping:
    def test_empty_text_returns_unchanged(self, default_scanner: Scanner) -> None:
        stripper = Stripper()
        result = stripper.strip("", [])
        assert result.clean_text == ""
        assert result.changed is False

    def test_no_matches_returns_unchanged(
        self, default_scanner: Scanner, copilot_block_text: str
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, [])
        assert result.clean_text == copilot_block_text
        assert result.changed is False

    def test_copilot_tips_block_removed(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, copilot_block_matches)
        assert "START COPILOT CODING AGENT TIPS" not in result.clean_text
        assert "END COPILOT CODING AGENT TIPS" not in result.clean_text

    def test_surrounding_content_preserved(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, copilot_block_matches)
        assert "Intro line." in result.clean_text
        assert "Outro line." in result.clean_text

    def test_result_changed_is_true(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, copilot_block_matches)
        assert result.changed is True

    def test_removed_spans_recorded(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, copilot_block_matches)
        assert result.match_count > 0

    def test_clean_is_shorter_than_original(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        result = stripper.strip(copilot_block_text, copilot_block_matches)
        assert len(result.clean_text) < len(result.original_text)

    def test_strip_text_convenience_method(
        self,
        copilot_block_text: str,
        copilot_block_matches: List[ScanMatch],
    ) -> None:
        stripper = Stripper()
        clean = stripper.strip_text(copilot_block_text, copilot_block_matches)
        assert isinstance(clean, str)
        assert "START COPILOT CODING AGENT TIPS" not in clean


# ---------------------------------------------------------------------------
# Stripper.strip — blank line collapsing
# ---------------------------------------------------------------------------


class TestBlankLineCollapsing:
    def test_excess_blank_lines_collapsed(self) -> None:
        from pr_clean.patterns import Severity, get_pattern_by_name

        text = "Before\n\n\n\n\nAfter\n"
        # No real injection patterns needed; just test the post-processing.
        stripper = Stripper()
        result = stripper.strip(text, [], collapse_blank_lines=True)
        # Collapse is applied even with no matches.
        assert "\n\n\n" not in result.clean_text

    def test_blank_line_collapse_disabled(self) -> None:
        text = "Before\n\n\n\n\nAfter\n"
        stripper = Stripper()
        result = stripper.strip(text, [], collapse_blank_lines=False)
        # Without collapse, excess blanks remain.
        assert "\n\n\n" in result.clean_text


# ---------------------------------------------------------------------------
# Stripper.strip — trailing whitespace
# ---------------------------------------------------------------------------


class TestTrailingWhitespaceStripping:
    def test_trailing_whitespace_removed(self) -> None:
        text = "line one   \nline two\t\nline three\n"
        stripper = Stripper()
        result = stripper.strip(text, [], strip_trailing_whitespace=True)
        for line in result.clean_text.splitlines():
            assert line == line.rstrip(), f"Trailing whitespace found in line: {line!r}"

    def test_trailing_whitespace_preserved_when_disabled(self) -> None:
        text = "line one   \nline two\n"
        stripper = Stripper()
        result = stripper.strip(
            text, [], strip_trailing_whitespace=False, collapse_blank_lines=False
        )
        assert "line one   " in result.clean_text


# ---------------------------------------------------------------------------
# Module-level convenience functions
# ---------------------------------------------------------------------------


class TestStripMatchesFunction:
    def test_returns_string(self, copilot_block_text: str, copilot_block_matches: List[ScanMatch]) -> None:
        clean = strip_matches(copilot_block_text, copilot_block_matches)
        assert isinstance(clean, str)

    def test_injection_removed(self, copilot_block_text: str, copilot_block_matches: List[ScanMatch]) -> None:
        clean = strip_matches(copilot_block_text, copilot_block_matches)
        assert "START COPILOT CODING AGENT TIPS" not in clean

    def test_empty_matches_returns_original(self) -> None:
        text = "No injections here."
        assert strip_matches(text, []) == text

    def test_empty_text_returns_empty(self) -> None:
        assert strip_matches("", []) == ""


class TestStripResultFunction:
    def test_returns_strip_result(self, copilot_block_text: str, copilot_block_matches: List[ScanMatch]) -> None:
        r = strip_result(copilot_block_text, copilot_block_matches)
        assert isinstance(r, StripResult)

    def test_result_changed(self, copilot_block_text: str, copilot_block_matches: List[ScanMatch]) -> None:
        r = strip_result(copilot_block_text, copilot_block_matches)
        assert r.changed is True

    def test_result_original_text_preserved(self, copilot_block_text: str, copilot_block_matches: List[ScanMatch]) -> None:
        r = strip_result(copilot_block_text, copilot_block_matches)
        assert r.original_text == copilot_block_text


# ---------------------------------------------------------------------------
# Integration: scan then strip the full sample fixture
# ---------------------------------------------------------------------------


class TestScanThenStrip:
    def test_fixture_has_matches(self, default_scanner: Scanner, sample_text: str) -> None:
        matches = default_scanner.scan(sample_text)
        assert len(matches) > 0

    def test_strip_removes_copilot_block_from_fixture(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        matches = default_scanner.scan(sample_text)
        clean = strip_matches(sample_text, matches)
        assert "START COPILOT CODING AGENT TIPS" not in clean
        assert "END COPILOT CODING AGENT TIPS" not in clean

    def test_human_content_preserved_in_fixture(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        matches = default_scanner.scan(sample_text)
        clean = strip_matches(sample_text, matches)
        # Human-authored content that should survive stripping.
        assert "Fix authentication timeout bug" in clean
        assert "Human-authored notes" in clean

    def test_clean_text_is_shorter_than_original(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        matches = default_scanner.scan(sample_text)
        clean = strip_matches(sample_text, matches)
        assert len(clean) < len(sample_text)

    def test_clean_text_has_no_excess_blank_lines(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        matches = default_scanner.scan(sample_text)
        clean = strip_matches(sample_text, matches)
        assert "\n\n\n" not in clean, "Excess blank lines found after stripping"

    def test_strip_result_records_removed_spans(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        matches = default_scanner.scan(sample_text)
        r = strip_result(sample_text, matches)
        assert r.match_count > 0

    def test_strip_result_to_dict_is_json_serialisable(
        self, default_scanner: Scanner, sample_text: str
    ) -> None:
        import json

        matches = default_scanner.scan(sample_text)
        r = strip_result(sample_text, matches)
        # Should not raise.
        serialised = json.dumps(r.to_dict())
        parsed = json.loads(serialised)
        assert parsed["changed"] is True


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestStripperEdgeCases:
    def test_match_at_very_start_of_text(self, default_scanner: Scanner) -> None:
        text = "Generated by GitHub Copilot\nThis is fine.\n"
        matches = default_scanner.scan(text)
        clean = strip_matches(text, matches)
        assert "Generated by GitHub Copilot" not in clean
        # The human line should survive.
        assert "This is fine." in clean

    def test_match_at_very_end_of_text(self, default_scanner: Scanner) -> None:
        text = "This is fine.\nGenerated by GitHub Copilot"
        matches = default_scanner.scan(text)
        clean = strip_matches(text, matches)
        assert "This is fine." in clean

    def test_multiple_matches_all_removed(self, default_scanner: Scanner) -> None:
        text = (
            "Intro.\n"
            "Generated by GitHub Copilot\n"
            "Middle.\n"
            "Powered by GitHub Copilot\n"
            "Outro.\n"
        )
        matches = default_scanner.scan(text)
        clean = strip_matches(text, matches)
        assert "Generated by GitHub Copilot" not in clean
        assert "Powered by GitHub Copilot" not in clean
        assert "Intro." in clean
        assert "Middle." in clean
        assert "Outro." in clean

    def test_text_with_only_injections_is_mostly_empty(self, default_scanner: Scanner) -> None:
        text = "Generated by GitHub Copilot\n"
        matches = default_scanner.scan(text)
        clean = strip_matches(text, matches)
        assert "Generated by GitHub Copilot" not in clean

    def test_custom_pattern_stripped(self) -> None:
        from pr_clean.config import load_config_from_dict

        cfg = load_config_from_dict(
            {
                "patterns": [
                    {
                        "name": "internal_bot",
                        "regex": r"INTERNAL BOT OUTPUT",
                        "severity": "high",
                        "confidence": 0.95,
                        "strip_full_block": True,
                    }
                ]
            }
        )
        scanner = Scanner.from_config(cfg)
        text = "Good content.\nINTERNAL BOT OUTPUT\nMore good content.\n"
        matches = scanner.scan(text)
        clean = strip_matches(text, matches)
        assert "INTERNAL BOT OUTPUT" not in clean
        assert "Good content." in clean
        assert "More good content." in clean
